
test :
	@cd Haskell; make test
	@cd Prolog; make test
	# @cd Postscript; make test
	# @cd C; make test

clean :
	cd Haskell; make clean
	cd Prolog; make clean
	cd Postscript; make clean
	cd C; make clean
